spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: none
  properties.hibernate.format_sql: true
  show-sql: true
spring.datasource:
  hikari.maximum-pool-size: 4
  url: ${DATASOURCE_URL}
  username: ${DATASOURCE_USERNAME}
  password: ${DATASOURCE_PASSWORD}
  platform: postgres
  driver-class-name: org.postgresql.Driver
jwt:
  secret-key: ${TOKEN_SECRET_KEY}
  #    //30days
  token:
    expired-time-ms: ${TOKEN_EXPIRE_TIME}
bot:
  token: ${BOT_TOKEN}
  username: ${BOT_USER_NAME}
  chatId: ${BOT_CHAT_ID}